name: Xcode
  
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    strategy:
      matrix:
    	  scheme: ['Mazes', 'MazeKit', 'MazeKitLib', 'Amaze']

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild -project Mazes.xcodeproj -scheme "${scheme}" -configuration Debug clean build 
